#!/usr/bin/env php
<?php
require_once "./vendor/autoload.php";

use Lite\Container\Container;
use Lite\Database\Driver\IDatabaseDriver;
use Lite\Database\Driver\PdoDriver;
use Lite\Database\Migration\Migrator;

$database = Container::singleton(IDatabaseDriver::class, PdoDriver::class);
$database->connect("pgsql", "db_test", "127.0.0.1", 5432, "postgres", "edcr");

$migrator = new Migrator(__DIR__ . "/database/migration", __DIR__ . "/src/Template/Migration", $database);

if ($argv[1] == "make:migration") {
    $migrator->make($argv[2]);
    return;
}

if ($argv[1] == "migrate") {
    $migrator->migrate();
}

if ($argv[1] == "rollback") {
    $steps = (isset($argv[2]) || isset($argv[3])) ? $argv[3] : null;
    $migrator->rollback($steps);
}
