#!/usr/bin/env php
<?php
require_once "./vendor/autoload.php";

use Lite\Database\Migration\Migrator;

$migrator = new Migrator(__DIR__ . "/database/migration", __DIR__ . "/src/Template/Migration");

if ($argv[1] == "make:migration") {
    $migrator->make($argv[2]);
}
